### PR TITLE
Issue 55 legend

### LINKED ISSUE #55: Add legend to game board

### PR DESCRIPTION
**Pull request by Luke-Sheltraw**
Closes #55 

Also converted all card images from PNG to WEBP to reduce load times. Looks like ~75% improvement on total data transferred for page load.

### CODE REVIEW

**Review by arjunghoshal — COMMENTED** [review]
The faster load time is really nice, but the legend gets cut off on the right
image

**Comment by Luke-Sheltraw** [comment]
@arjunghoshal what are your screen dimensions?

**Comment by arjunghoshal** [comment]
1920 x 1080, but I’m getting the cutoff even if I change dimensions with dev tools

**Comment by Luke-Sheltraw** [comment]
@arjunghoshal PR #63 moved the main layout of the game board from being display: flex to display: grid, so I pulled that change in here just to make sure we aren't trying to fix something that will be thrown away anyway. 

On my side, it (still) appears that the legend isn't clipping. Can you take another look, and lmk if the display: grid fixed that or if I should take another look.

**Comment by arjunghoshal** [comment]
Looks like display: grid fixed it, thanks for the fix!

**Review by arjunghoshal — APPROVED** [review]
LGTM

**Pull request merged**
